package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/leandrobraga/goexpert-desafio-cleanarch/internal/infra/graph/model"
	"github.com/leandrobraga/goexpert-desafio-cleanarch/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.OrderInput) (*model.Order, error) {
	dto := usecase.OrderInputDTO{
		ID:    input.ID,
		Price: input.Price,
		Tax:   input.Tax,
	}
	output, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         output.ID,
		Price:      output.Price,
		Tax:        output.Tax,
		FinalPrice: output.FinalPrice,
	}, nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, input model.OrderListInput) ([]*model.Order, error) {
	dto := usecase.ListOrdersInputDTO{
		Limit: *input.Limit,
		Page:  *input.Page,
		Sort:  *input.Sort,
	}
	output, err := r.ListOrdersUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}
	var orders []*model.Order
	for _, orderDTO := range output {
		order := &model.Order{
			ID:         orderDTO.ID,
			Price:      orderDTO.Price,
			Tax:        orderDTO.Tax,
			FinalPrice: orderDTO.FinalPrice,
		}
		orders = append(orders, order)
	}

	return orders, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
